import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f7f8fa",
    padding: 24,
  },
  header: {
    fontSize: 24,
    fontWeight: "600",
    color: "#333",
    textAlign: "center",
    marginVertical: 12,
  },
  emptyText: {
    color: "#888",
    textAlign: "center",
    marginTop: 20,
    fontSize: 15,
  },
  journalCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#eee",
  },
  journalDate: {
    color: "#4f9cf9",
    fontWeight: "500",
    marginBottom: 4,
  },
  journalText: {
    color: "#333",
    fontSize: 15,
  },
  fabButton: {
    position: "absolute",
    bottom: 25,
    right: 25,
    backgroundColor: "#4f9cf9",
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  recordSection: {
    alignItems: "center",
    marginBottom: 20,
  },
  recordButton: {
    width: 70,
    height: 70,
    borderRadius: 35,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  recordStatus: {
    marginTop: 10,
    fontSize: 16,
    color: "#555",
  },
  transcriptBox: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    marginTop: 12,
    maxHeight: 150,
    width: "100%",
  },
  transcriptText: {
    color: "#333",
    fontSize: 15,
  },
  saveButton: {
    backgroundColor: "#4f9cf9",
    paddingVertical: 12,
    borderRadius: 25,
    alignItems: "center",
  },
  saveButtonText: {
    color: "#fff",
    fontWeight: "500",
    fontSize: 16,
  },
  journalDetailCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#eee",
    marginTop: 10,
  },
  moodScoreContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#eee",
  },
  moodScoreLabel: {
    fontSize: 15,
    color: "#666",
    fontWeight: "500",
  },
  moodScoreValue: {
    fontSize: 18,
    color: "#4f9cf9",
    fontWeight: "bold",
  },
  journalCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  moodScoreBadge: {
    backgroundColor: "#e8f4fd",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  moodScoreBadgeText: {
    color: "#4f9cf9",
    fontSize: 12,
    fontWeight: "600",
  },
  deleteButton: {
    position: "absolute",
    top: 32,
    right: 12,
    padding: 8,
  },
});
